#  API CALLS
register:
  path: /api/register
  controller: App\Controller\Rest\AuthController::register
  methods: POST
api_login_check:
  path: /api/login_check
  controller: App\Controller\Rest\AuthController::getTokenUser
test:
  path: /api/test
  controller: App\Controller\Rest\ApiController::test



#  WEB CALLS

   
# app_cv:
#    path: /cv_sofrecom/{firstname}/{lastname}/{age?0}/{address}
#    controller: App\Controller\Web\CvController::index
#    methods: [GET,POST]
#    defaults:
#       firstname: Sofrecom
#       lastname: Sofrecom
#       age: 0
#       address: casa
#    requirements:
#       age: \d{1,2}
#       address: casa|rabat

# app_cv_test:
#    path: /cv_sofrecom/{firstname}/{lastname}/{age?0}/{address}
#    controller: App\Controller\Web\CvController::test
#    methods: [GET]


# route_name_1:
#     path: /path1
#     controller: App\Controller\ExampleController::multipleRoutesAction

# route_name_2:
#     path: /path2
#     controller: App\Controller\ExampleController::multipleRoutesAction